# Generated by Django 6.0.5 on 2026-05-19 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_verification_otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_password_reset_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_2fa_otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_email_change_otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=128, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.IntegerField(default=0)),
                ('otp_locked_until', models.DateTimeField(blank=True, null=True)),
                ('password_reset_otp', models.CharField(blank=True, max_length=128, null=True)),
                ('password_reset_otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('password_reset_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('password_reset_otp_attempts', models.IntegerField(default=0)),
                ('password_reset_otp_locked_until', models.DateTimeField(blank=True, null=True)),
                ('pending_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('pending_email_otp', models.CharField(blank=True, max_length=128, null=True)),
                ('pending_email_otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('pending_email_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('pending_email_otp_attempts', models.IntegerField(default=0)),
                ('pending_email_otp_locked_until', models.DateTimeField(blank=True, null=True)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('two_fa_method', models.CharField(blank=True, choices=[('email', 'Email OTP')], default='email', max_length=20, null=True)),
                ('two_fa_otp', models.CharField(blank=True, max_length=128, null=True)),
                ('two_fa_otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('two_fa_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('two_fa_attempts', models.IntegerField(default=0)),
                ('two_fa_locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_jti', models.CharField(blank=True, max_length=255, null=True)),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('browser', models.CharField(blank=True, max_length=255, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, max_length=100, null=True)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('location_region', models.CharField(blank=True, max_length=100, null=True)),
                ('location_country', models.CharField(blank=True, max_length=100, null=True)),
                ('location_timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TwoFALog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('setup', 'Setup 2FA'), ('enable', 'Enable 2FA'), ('verify', 'Verify 2FA'), ('disable', 'Disable 2FA'), ('failed_attempt', 'Failed 2FA Attempt')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_fa_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_time'],
            },
        ),
    ]
