# Generated by Django 6.0.6 on 2026-06-15 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ResultGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=100)),
                ('grade_num', models.PositiveSmallIntegerField()),
                ('percentage_from', models.PositiveSmallIntegerField()),
                ('percentage_to', models.PositiveSmallIntegerField()),
                ('status', models.CharField(default='A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('father', models.CharField(max_length=255)),
                ('mother', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='A', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.CreateModel(
            name='ResultMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_number', models.PositiveSmallIntegerField()),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_date', models.DateField()),
                ('status', models.CharField(default='A', max_length=2)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='Student.examname')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='Student.resultgrade')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='Student.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='Student.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Student.studentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='A', max_length=2)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_admissions', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='Student.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='Student.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='Student.studentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ResultDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(default='A', max_length=2)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_details', to='Student.examname')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_details', to='Student.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_details', to='Student.section')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_details', to='Student.resultgrade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_details', to='Student.studentinfo')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_details', to='Student.subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='A', max_length=2)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subjects', to='Student.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subjects', to='Student.studentinfo')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subjects', to='Student.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
