# Generated by Django 6.0.6 on 2026-06-16 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_examname_resultgrade_studentinfo_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Student.class'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Student.class'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='Student.class'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='Student.section'),
        ),
        migrations.AlterField(
            model_name='resultdetails',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_details', to='Student.examname'),
        ),
        migrations.AlterField(
            model_name='resultdetails',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_details', to='Student.resultgrade'),
        ),
        migrations.AlterField(
            model_name='resultdetails',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_details', to='Student.class'),
        ),
        migrations.AlterField(
            model_name='resultdetails',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_details', to='Student.section'),
        ),
        migrations.AlterField(
            model_name='resultdetails',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_details', to='Student.subject'),
        ),
        migrations.AlterField(
            model_name='resultmain',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Student.examname'),
        ),
        migrations.AlterField(
            model_name='resultmain',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Student.resultgrade'),
        ),
        migrations.AlterField(
            model_name='resultmain',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Student.class'),
        ),
        migrations.AlterField(
            model_name='resultmain',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Student.section'),
        ),
    ]
